"""
POST /api/v1/explain

Takes a completed prediction (symbol, model, prediction, confidence, SHAP
features, technical indicators) and returns a plain-English analyst brief
generated by an LLM.

Priority:
  1. Groq  (llama-3.3-70b-versatile) — fast, free tier
  2. Gemini (gemini-1.5-flash)        — fallback if GROQ_API_KEY not set
"""
from __future__ import annotations

import os
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()


# ── Request / Response schemas ────────────────────────────────────────────────

class IndicatorsPayload(BaseModel):
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    rsi: Optional[float] = None
    macd: Optional[float] = None


class ShapFeature(BaseModel):
    feature: str
    impact: float


class ExplainRequest(BaseModel):
    symbol: str
    model_name: str
    prediction: str          # "UP" or "DOWN"
    confidence: float        # 0.0–1.0
    overfit_status: Optional[str] = None
    explanation: list[ShapFeature] = []
    indicators: Optional[IndicatorsPayload] = None


class ExplainResponse(BaseModel):
    summary: str             # 2–3 paragraph plain-English brief
    provider: str            # "groq" | "gemini" | "fallback"


# ── Prompt builder ────────────────────────────────────────────────────────────

def _build_prompt(req: ExplainRequest) -> str:
    horizon = (
        "3-day" if "3d" in req.model_name else
        "5-day" if "5d" in req.model_name else
        "next-day"
    )
    direction = "upward" if req.prediction == "UP" else "downward"
    confidence_pct = req.confidence * 100

    # Top 5 SHAP features sorted by absolute impact
    top_shap = sorted(req.explanation, key=lambda f: abs(f.impact), reverse=True)[:5]

    # Build rich feature descriptions
    shap_detail_lines = []
    for f in top_shap:
        name = f.feature.replace("_", " ").lower()
        direction_word = "bullish" if f.impact > 0 else "bearish"
        sign = "+" if f.impact > 0 else ""
        shap_detail_lines.append(f"  • {name}: {sign}{f.impact:.4f} ({direction_word})")
    shap_block = "\n".join(shap_detail_lines) if shap_detail_lines else "  (no SHAP data available)"

    # Build rich indicator context
    ind = req.indicators
    indicator_context_parts = []
    if ind:
        if ind.sma_20 is not None and ind.sma_50 is not None:
            sma_rel = "above both" if ind.sma_20 > ind.sma_50 else "below the 50-day"
            indicator_context_parts.append(
                f"SMA(20)={ind.sma_20:.2f} is {sma_rel} SMA(50)={ind.sma_50:.2f} "
                f"({'short-term bullish trend structure' if ind.sma_20 > ind.sma_50 else 'short-term weakness vs medium-term trend'})"
            )
        elif ind.sma_20 is not None:
            indicator_context_parts.append(f"SMA(20)={ind.sma_20:.2f}")

        if ind.rsi is not None:
            if ind.rsi > 70:
                rsi_ctx = f"RSI(14)={ind.rsi:.1f} — overbought territory, potential reversal risk"
            elif ind.rsi < 30:
                rsi_ctx = f"RSI(14)={ind.rsi:.1f} — oversold territory, potential mean reversion"
            elif ind.rsi > 55:
                rsi_ctx = f"RSI(14)={ind.rsi:.1f} — above mid-line, momentum leaning bullish"
            elif ind.rsi < 45:
                rsi_ctx = f"RSI(14)={ind.rsi:.1f} — below mid-line, momentum leaning bearish"
            else:
                rsi_ctx = f"RSI(14)={ind.rsi:.1f} — neutral momentum"
            indicator_context_parts.append(rsi_ctx)

        if ind.macd is not None:
            macd_ctx = (
                f"MACD={ind.macd:.4f} ({'positive — bullish crossover regime' if ind.macd > 0 else 'negative — bearish crossover regime'})"
            )
            indicator_context_parts.append(macd_ctx)

    indicators_block = "\n".join(f"  • {p}" for p in indicator_context_parts) if indicator_context_parts else "  (no indicator data)"

    model_clean = req.model_name.replace("_", " ").title()
    overfit_note = ""
    if req.overfit_status:
        if "OVERFIT" in req.overfit_status:
            overfit_note = (
                "Important caveat: the model shows signs of overfitting "
                f"({req.overfit_status}), so this forecast carries additional uncertainty."
            )
        else:
            overfit_note = f"Model quality check: {req.overfit_status} — generalisation is acceptable."

    confidence_note = (
        "The confidence level is high, reinforcing the signal strength."
        if confidence_pct >= 70 else
        "The confidence level is moderate — treat this as a probabilistic lean rather than a firm call."
        if confidence_pct >= 55 else
        "The confidence level is low — this is a marginal signal and should be weighted accordingly."
    )

    return f"""You are a senior quantitative analyst at a systematic hedge fund. Your job is to write a concise, plain-English market brief for a portfolio manager based on a model output.

=== MODEL OUTPUT ===
Ticker:        {req.symbol}
Model:         {model_clean}
Forecast:      {req.prediction} over {horizon} horizon
Confidence:    {confidence_pct:.1f}%

=== KEY DRIVERS (SHAP) ===
{shap_block}

=== TECHNICAL CONTEXT ===
{indicators_block}

=== MODEL RELIABILITY ===
{overfit_note if overfit_note else 'No overfitting issues detected.'}
{confidence_note}

=== INSTRUCTIONS ===
Write exactly 2–3 tight paragraphs:

Paragraph 1 — Forecast summary: State the directional call, the horizon, and the confidence level. Frame it as a probabilistic view, not a certainty.

Paragraph 2 — Driver analysis: Explain what the top SHAP features actually mean in market terms. Connect the dots — e.g. if RSI is overbought AND MACD is positive AND price is above its 20-day SMA, explain what that combination typically signals and why the model is reading it as {direction} pressure. Be specific to {req.symbol}.

Paragraph 3 (optional, only if warranted) — Risks and caveats: If there are conflicting signals (e.g. overbought RSI but bullish SHAP drivers), if confidence is below 60%, or if the model has overfitting concerns, state this clearly. If everything is consistent, skip this paragraph.

Rules:
- No bullet points, no headers, no markdown
- Do not use the word "AI" — say "the model" or "the analysis"  
- Write like a human analyst, not a chatbot — direct, precise, no filler phrases like "it's worth noting"
- Max 220 words total"""


# ── LLM callers ──────────────────────────────────────────────────────────────

def _call_groq(prompt: str) -> str:
    """Call Groq's chat completion API using httpx (no SDK needed)."""
    import httpx

    api_key = os.getenv("GROQ_API_KEY", "")
    if not api_key:
        raise ValueError("GROQ_API_KEY not set")

    resp = httpx.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={
            "model": "llama-3.3-70b-versatile",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 350,
            "temperature": 0.4,
        },
        timeout=20.0,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def _call_gemini(prompt: str) -> str:
    """Call Gemini Flash via REST API."""
    import httpx

    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not set")

    resp = httpx.post(
        f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}",
        json={
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"maxOutputTokens": 350, "temperature": 0.4},
        },
        timeout=20.0,
    )
    resp.raise_for_status()
    return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.post("/explain", response_model=ExplainResponse, tags=["Explainability"])
def explain_prediction(req: ExplainRequest):
    """
    Generate a plain-English analyst brief for a completed prediction.
    Uses Groq (llama-3.3-70b) with Gemini as fallback.
    """
    prompt = _build_prompt(req)

    # Try Groq first
    if os.getenv("GROQ_API_KEY"):
        try:
            text = _call_groq(prompt)
            return ExplainResponse(summary=text, provider="groq")
        except Exception as e:
            print(f"Groq failed: {e} — trying Gemini")

    # Try Gemini second
    if os.getenv("GEMINI_API_KEY"):
        try:
            text = _call_gemini(prompt)
            return ExplainResponse(summary=text, provider="gemini")
        except Exception as e:
            print(f"Gemini failed: {e}")

    raise HTTPException(
        status_code=503,
        detail="No LLM API key configured. Set GROQ_API_KEY or GEMINI_API_KEY in your environment.",
    )
