"""Add train_accuracy and overfit_status to ModelRegistry

Revision ID: 24ad19d51463
Revises: 0e836bfecc39
Create Date: 2026-07-26 05:47:05.733199+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ad19d51463'
down_revision: Union[str, Sequence[str], None] = '0e836bfecc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('train_accuracy', sa.Float(), nullable=True))
    op.add_column('model_registry', sa.Column('overfit_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'overfit_status')
    op.drop_column('model_registry', 'train_accuracy')
    # ### end Alembic commands ###
