"""Initial tables

Revision ID: efea92b7aa0b
Revises: da8732632fe7
Create Date: 2026-07-25 06:42:09.736521+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'efea92b7aa0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
