"""add total_price_rows to model_registry

Revision ID: f50a04ab5936
Revises: c6187c69f51f
Create Date: 2026-07-25 11:11:40.402135+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50a04ab5936'
down_revision: Union[str, Sequence[str], None] = 'c6187c69f51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('total_price_rows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'total_price_rows')
    # ### end Alembic commands ###
